spring.application.name=bot-io
server.port=8090
the.bot.configFile=${BOT_CONFIG_FILE:}
the.bot.runtimeDir=./runtime/
the.bot.dataDir=./runtime/data/
the.bot.logDir=./runtime/logs/
the.bot.rest.bot-engine-base-url=${THE_BOT_REST_BOT_ENGINE_BASE_URL:http://bot-engine:8100}
logging.level.org.freakz=DEBUG
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
