version: '2.4'
services:
  #  Hokan the Bot engine container
  bot-engine:
    image: ghcr.io/petria/the_bot-engine:${IMAGE_TAG:-latest}
    volumes:
      - /home/hokan/the_bot/runtime:/runtime
      - /home/hokan/the_bot/config:/config
    ports:
      - "127.0.0.1:8100:8100"
    environment:
      - TZ="Europe/Helsinki"
      - hokan.runtime.profile=DEV
    container_name: bot-engine
  #  Hokan the Bot io container
  bot-io:
    image: ghcr.io/petria/the_bot-io:${IMAGE_TAG:-latest}
    volumes:
      - /home/hokan/the_bot/runtime:/runtime
      - /home/hokan/the_bot/config:/config
    ports:
      - "127.0.0.1:8090:8090"
    environment:
      - TZ="Europe/Helsinki"
      - hokan.runtime.profile=DEV
    container_name: bot-io
networks:
  default:
    driver: bridge
