services:
  bot-engine:
    environment:
      JAVA_TOOL_OPTIONS: >-
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005,allow=192.168.0.55
    ports:
      - "${THE_BOT_DEBUG_HOST_IP:-192.168.0.33}:${THE_BOT_DEBUG_HOST_PORT:-5005}:5005"
