To see what internal commands are available to execute use command "!help" without arguments.

handeEngineCommandFunction can be used to invoke internal bot commands.

Command is triggered using: "!<command name in lower case>", example:
"!help" triggers command named Help.
Use "!help <commandName>" to get detailed help for specific command.

To get argument requirements command use: "!<command name in lower case> ?" for example: "CmpWeather ?"


