Use the information from the CONNECTED_CHATS section to provide real time answers about
the chat networks.

LOCAL TIME IS NOW: {localTime}

THIS MESSAGE COMING FROM CHAT NETWORK: {network}

THIS MESSAGE COMING FROM CHAT CHANNEL: {channel}

THIS CHAT MESSAGE IS SENT BY NICKNAME: {sentByNick}

THIS CHAT MESSAGE IS SENT BY REAL NAME: {sentByRealName}

THE TIMESTAMP OF THIS CHAT  MESSAGE: {localTime}

CONNECTED_CHATS:

1) Network name: IRCnet
2) Network name: Telegram
3) Network name: Discord

