server.port=8100
the.bot.configFile=${BOT_CONFIG_FILE:}
the.bot.runtimeDir=./runtime/
the.bot.dataDir=./runtime/data/
the.bot.logDir=./runtime/logs/
#management.endpoints.web.exposure.include=*
logging.level.org.freakz=DEBUG
