spring.application.name=bot-engine
server.port=8100
the.bot.configFile=${BOT_CONFIG_FILE:}
the.bot.runtimeDir=./runtime/
the.bot.dataDir=./runtime/data/
the.bot.logDir=./runtime/logs/
the.bot.webPublicBaseUrl=${THE_BOT_WEB_PUBLIC_BASE_URL:http://localhost:8091}
the.bot.rest.bot-io-base-url=${THE_BOT_REST_BOT_IO_BASE_URL:http://bot-io:8090}
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
logging.level.org.freakz=DEBUG
