hokan.runtime.profile=DEV
the.bot.runtimeDir=./
the.bot.dataDir=./data/
the.bot.logDir=./logs/
the.bot.runtimeConfigFile=./DEV.the_bot_config.json
hokan.node-context-secret=${HOKAN_NODE_CONTEXT_SECRET:}
weather.api-key=${WEATHER_API_KEY}
weather.api-url=${WEATHER_API_URL:http://api.weatherapi.com/v1}
channel.do.sys.notify=
